name: 'Gradle command action'
description: 'standardizes the CLI flags for gradle'
inputs:
  args:
    required: true
runs:
  using: "composite"
  steps: 
    - run: |
          ./gradlew ${{ inputs.args }} --info --max-workers=2 -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.console=plain --continue
      shell: sh
