name: validate actions
on:
  push:
  pull_request:
  release:
    types: 
      - created
  workflow_dispatch:

jobs:
  validate-actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nwisbeta/validate-yaml-schema@v1.0